USE trabalho_nosql;

LOAD DATA LOCAL INFILE '/home/nosql/dataset/AK.TXT' 
INTO TABLE names 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'; 

LOAD DATA LOCAL INFILE '/home/nosql/dataset/OK.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/MS.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 

LOAD DATA LOCAL INFILE '/home/nosql/dataset/NV.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/NJ.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/WI.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/DE.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/CA.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/WY.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/GA.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/IA.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/ND.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/OR.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/DC.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/AL.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/MN.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/VA.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/MT.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/AR.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/KS.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/WA.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/NE.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/SD.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/VT.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/MD.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/CO.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/MI.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/IN.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/SC.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/IL.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/ID.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/NY.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/TX.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/KY.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/FL.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/UT.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/MO.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/RI.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/CT.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/WV.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/PA.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/NH.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/LA.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/NM.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/MA.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/NC.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/AZ.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/ME.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/OH.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/TN.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE '/home/nosql/dataset/HI.TXT' INTO TABLE names FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
